- BackEnd/src/main/java/com/capstone/pathproject/controller/TestApiController.java
> main(master) 브랜치로 merge 요청

- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Member.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/memberGender.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/memberType.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/Mobility.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityCompany.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityPayment.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityReservation.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityReservationResult.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityState.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityType.java
퍼스널 모빌리티쪽 DB 전부 생성 및 매핑 완료.
물리명과 테이블명 변경과 추가된 점이 있음.
물리명은 대부분 바뀌었음.
mobility_reservation 테이블에서 예약결과 필드 추가됨.
> [백]퍼스널모빌리티DB 생성 및 매핑

- BackEnd/src/main/java/com/capstone/pathproject/controller/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/TestApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Member.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/MemberDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/service/MemberService.java
- BackEnd/src/test/java/com/capstone/pathproject/controller/MemberApiControllerTest.java
기존 정적 팩토리 메서드 생성자에서 Builder패턴 생성자로 변경하였음.
값을 받는 인자들이 많아서 Builder 패턴 생성자가 더 효율적이고 생산적이었음. 이에 따라 변경된 점들이 많음
Member 필드가 많으므로 기존 RequestParam으로 적었던 것이 비효율적이므로 데이터 값을 받는 DTO를 생성하였음.
메서드명을 User -> Member 변경
많은 RequestParam을 MemberDTO로 변경하였음.
객체 생성같은 경우 Builder패턴으로 생성하였으며, DTO의 메서드로 member객체를 생성하여 가져옴
> [백]Member 수정 및 추가

- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Company.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/DetailOption.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Option.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/ProdBasic.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Product.java
Product, prod_basic, option, detail_option
table entity mapping
> [백]Company DB Create

- BackEnd/src/main/java/com/capstone/pathproject/controller/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Member.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/Mobility.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityCompany.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/MemberDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/response/Message.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/response/StatusEnum.java
- BackEnd/src/main/java/com/capstone/pathproject/service/MemberService.java
- BackEnd/src/test/java/com/capstone/pathproject/controller/MemberApiControllerTest.java
- dto/response 폴더 안에 있는 Message 클래스에서 변수명을 변경하였음.
- status -> header, data -> body
- body는 Object 타입에서 제네릭 타입으로 변경하였음( 추후 확장성 고려 )
- 생성자는 Builder 패턴 적용
- 기존 Entity로 반환하던 것을 DTO로 변경
- 양방향이 필요할 시 추가하는 것으로 함
> [백]response, Entity, 회원가입 기능 수정

- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Member.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/Mobility.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityCompany.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityPayment.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityReservation.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityState.java
> [백] 물리명 변경

- BackEnd/src/main/java/com/capstone/pathproject/domain/community/Post.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/community/PostType.java
커뮤니티의 게시글 POST 테이블 매핑 및 엔티티 생성 완료
> [백] 커뮤니티 엔티티 생성

- BackEnd/src/main/java/com/capstone/pathproject/controller/MemberApiController.java
- front-end/src/routes/Member/signUp.js
- front-end/src/setupProxy.js
> [프론트] 회원가입 통신 설정

- BackEnd/src/main/java/com/capstone/pathproject/controller/CarPoolPostAPIController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/CarPoolPostWebController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/carpool/CarPoolPost.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/CarPoolPostDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/CarPoolPostRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/CarPoolPostService.java
> [백]카풀 게시글 등록

- BackEnd/src/main/java/com/capstone/pathproject/controller/CarPoolPostWebController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/VehicleAPIController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/VehicleWebController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/carpool/CarPoolPost.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/carpool/Vehicle.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/CarPoolPostDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/VehicleDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/CarPoolPostRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/VehicleRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/CarPoolPostService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/VehicleService.java
- BackEnd/src/main/resources/templates/carpost.html
- BackEnd/src/main/resources/templates/vehicle.html
CarPool게시판
-crud 완성
차량 테이블
- 매핑완료
- crud 완성
> [백]카풀게시판 / 차량테이블

- BackEnd/src/main/java/com/capstone/pathproject/controller/CompanyApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/ProductApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Company.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Product.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/CompanyDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/ProductDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/service/CompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/ProductService.java
- front-end/.idea/front-end.iml
- front-end/.idea/misc.xml
- front-end/.idea/modules.xml
- front-end/.idea/vcs.xml
- front-end/.idea/workspace.xml
company table
create, read, update, delete
product table CRUD 틀 작성
> [백]Company CRUD

- BackEnd/build.gradle
- BackEnd/src/main/java/com/capstone/pathproject/controller/ApiControllerAdvice.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/excpetion/ApiControllerAdvice.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/member/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Member.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Role.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/memberType.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/member/LoginRequestDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/member/MemberDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/response/Message.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/MemberRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/member/MemberRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/security/auth/PrincipalDetails.java
- BackEnd/src/main/java/com/capstone/pathproject/security/auth/PrincipalDetailsService.java
- BackEnd/src/main/java/com/capstone/pathproject/security/auth/jwt/JwtAuthenticationFilter.java
- BackEnd/src/main/java/com/capstone/pathproject/security/auth/jwt/JwtAuthorizationFilter.java
- BackEnd/src/main/java/com/capstone/pathproject/security/auth/jwt/JwtProperties.java
- BackEnd/src/main/java/com/capstone/pathproject/security/config/CorsConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/security/config/SecurityConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/service/CompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/MemberService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/member/MemberService.java
- BackEnd/src/test/java/com/capstone/pathproject/controller/MemberApiControllerTest.java
- front-end/src/routes/Member/signUp.js
- 스프링 시큐리티 적용
- 토큰 인증 기반 로그인 적용
- 유효성 검사 로직 수정 : `@Vaild` 적용
- 회원가입 테스트 완료
- cors 설정으로 프론트에서 /api 경로 요청 가능
> Spring security

- BackEnd/src/main/java/com/capstone/pathproject/controller/ProductApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/TestApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/DetailOption.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Option.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Product.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/DetailOptionDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/OptionDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/ProductDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/DetailOptionRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/OptionRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/ProductService.java
- BackEnd/src/main/resources/rest/Product.http
- BackEnd/src/main/resources/rest/member.json
- BackEnd/src/main/resources/rest/option.http
- BackEnd/src/main/resources/rest/prodBasic.http
상품 옵션 create updeate delete
상품 세부옵션 create update delete
> [백]product_CRUD

- BackEnd/src/main/java/com/capstone/pathproject/controller/excpetion/ApiControllerAdvice.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/member/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Card.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Search.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Sns.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/Mobility.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityCompany.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityPayment.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityReservation.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/response/Message.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/member/MemberRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/mobility/MobilityCompanyRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/mobility/MobilityRepository.java
- BackEnd/src/test/java/com/capstone/pathproject/domain/mobility/MobilityCompanyTest.java
프론트쪽에서 안받아져서 Http 상태 수정
- 전부 HttpStatus.OK 로 수정
> [백] ResponseEntity 에러 수정

- BackEnd/src/main/java/com/capstone/pathproject/controller/CompanyApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/community/Post.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/company/CompanyDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/CompanyRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/CompanyService.java
- BackEnd/src/main/resources/rest/company.json
- BackEnd/src/main/resources/rest/member.json
- BackEnd/src/main/resources/rest/member/POST_회원가입.http
- BackEnd/src/main/resources/rest/member/member.json
- BackEnd/src/test/java/com/capstone/pathproject/repository/CompanyRepositoryTest.java
> [백]company 조회

- BackEnd/src/main/java/com/capstone/pathproject/controller/ProductApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/product/ProdBasicDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/service/ProductService.java
prodBasic 파일 업로드
productApiController URL 수정
> [백] productBasic 파일 업로드

- front-end/src/routes/Member/Login/LoginContainer.js
- front-end/src/routes/Member/Login/LoginPresenter.js
> [프론트] 로그인 페이지 수정

- front-end/src/routes/Member/SignUp/SignUpContainer.js
- front-end/src/routes/Member/SignUp/SignUpPresenter.js
> [프론트] 회원가입 페이지 수정

- front-end/src/components/Router.js
- front-end/src/routes/Member/Login/LoginPresenter.js
- front-end/src/routes/Member/SignUp/SignUpPresenter.js
- front-end/src/routes/Member/Update/UpdateMemContainer.js
- front-end/src/routes/Member/Update/UpdateMemPresenter.js
- front-end/src/routes/Member/index.js
- front-end/src/routes/Member/listItems.js
- 라우터 추가
- 회원 수정 페이지 추가
- 회원 수정 페이지 이동 기능 추가
- 회원 수정 기능 연결
> [프론트] 회원수정 페이지 추가

- front-end/src/routes/Member/Login/LoginContainer.js
- front-end/src/routes/Member/Login/LoginPresenter.js
- front-end/src/routes/Member/MemberContainer.js
- front-end/src/routes/Member/MemberPresenter.js
- front-end/src/routes/Member/SearchId/SearchIdContainer.js
- front-end/src/routes/Member/SearchId/SearchIdPresenter.js
- front-end/src/routes/Member/SearchPw/SearchPwContainer.js
- front-end/src/routes/Member/SearchPw/SearchPwPresenter.js
- front-end/src/routes/Member/SignUp/SignUpContainer.js
- front-end/src/routes/Member/SignUp/SignUpPresenter.js
- front-end/src/routes/Member/Update/UpdateMemContainer.js
- front-end/src/routes/Member/Update/UpdateMemPresenter.js
- 선언한 변수는 위
- useEffect는 아래로 변경
> [프론트] Member 코드 위치 변경

- front-end/src/routes/Member/Company/CompManage/CompManage.js
- front-end/src/routes/Member/Company/CompManage/CompManageContainer.js
- front-end/src/routes/Member/Company/CompManage/ItemEdit/ItemEdit.js
- front-end/src/routes/Member/Company/CompManage/ItemEdit/ItemEditContainer.js
- front-end/src/routes/Member/Company/CompManage/Items/Item.js
- front-end/src/routes/Member/Company/CompManage/Items/ItemContainer.js
> [프론트]Company

- BackEnd/src/main/java/com/capstone/pathproject/controller/member/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/service/member/MemberService.java
- front-end/public/index.html
- front-end/src/components/Router.js
- front-end/src/routes/WalkPath/WalkPathContainer.js
- front-end/src/routes/WalkPath/WalkPathPresenter.js
- front-end/src/routes/WalkPath/index.js
Tmap API로 가서 회원가입하여 appkey키를 발급받고 `.env`파일에 다음 줄을 추가하여야함.
`REACT_APP_TMAP_API="발급받은 appkey키"`
> T map api 추가

- BackEnd/src/main/java/com/capstone/pathproject/util/JwtTokenUtil.java
-  AccessToken의 payload에 유저 Role 추가
> [백] AccessToken 값 추가

- front-end/src/components/Router.js
- front-end/src/routes/FileTest/FileTestContainer.js
- front-end/src/routes/FileTest/FileTestPresenter.js
- front-end/src/routes/FileTest/index.js
- File 업로드, 출력, 다운 테스트용 페이지 추가
> [프론트] File 관련 테스트할 페이지 생성

- BackEnd/src/main/java/com/capstone/pathproject/controller/file/UploadFileApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/file/UploadFile.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/file/FileForm.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/file/UploadFileDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/file/UploadFileRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/file/UploadFileService.java
- File 테이블 생성
- File 업로드, 출력, 다운 기능 추가
- File DTO 생성
> [백] File 추가

- front-end/src/routes/Community/CommunityContents.js
Reverts YGUniv-NonSleep/Path#130
> Revert "Update CommunityContents.js"

- BackEnd/src/main/java/com/capstone/pathproject/controller/post/PostApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/community/PostType.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/community/PostRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/community/PostService.java
- front-end/src/components/Router.js
- front-end/src/routes/Community/CommunityAdd.js
- front-end/src/routes/Community/CommunityContainer.js
- front-end/src/routes/Community/CommunityContents.js
- front-end/src/routes/Community/CommunityPresenter.js
- front-end/src/routes/Community/index.js
> [백,프론트] 게시글 모든 기능 구현 완

- front-end/src/routes/Community/CommunityContainer.js
> [백.프론트] 게시글 구현 완(최종)

- BackEnd/src/main/java/com/capstone/pathproject/controller/company/CompanyApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Company.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Member.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/company/CompanyDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/member/MemberDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/product/DetailOptionDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/service/product/ProductService.java
companyDTO에 포함되어있던 member domain ->member dto
> [백]CompanyDTO 수정

- BackEnd/src/main/java/com/capstone/pathproject/controller/UtilApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/company/CompanyApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/product/ProductApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/service/product/ProductService.java
UtilApiController image저장 함수 추가
product Basic create, patch 수정
> [백]image 저장 수정

- BackEnd/src/main/java/com/capstone/pathproject/config/SecurityConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/excpetion/ApiControllerAdvice.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/excpetion/ExceptionApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/response/StatusEnum.java
- BackEnd/src/main/java/com/capstone/pathproject/security/auth/jwt/JwtAuthenticationFilter.java
- BackEnd/src/main/java/com/capstone/pathproject/security/auth/jwt/JwtAuthorizationFilter.java
- BackEnd/src/main/java/com/capstone/pathproject/security/filter/JwtExceptionFilter.java
- BackEnd/src/main/java/com/capstone/pathproject/security/filter/LogFilter.java
- BackEnd/src/main/java/com/capstone/pathproject/util/CookieUtil.java
- front-end/src/components/Menubar.js
- front-end/src/routes/Member/Login/LoginContainer.js
- 불필요한 접근 삭제
- 예외 처리
- 아이디 일치하지 않을 때
- 비밀번호 일치하지 않을 때
- RefreshToken값이 Redis에 없을 때
> [백] 스프링 시큐리티 최적화 및 예외처리

- BackEnd/build.gradle
- BackEnd/src/main/java/com/capstone/pathproject/config/CorsConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/config/rest/KakaoConfiguration.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/KakaoApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/security/auth/jwt/JwtAuthorizationFilter.java
- application.yml에 `api.kakao` 추가해서 `Controller` 양식에 맞게 신호보내면 그대로 응답해줌
> [백] 서버에서 카카오API 호출

- BackEnd/src/main/java/com/capstone/pathproject/config/rest/OdsayConfiguration.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/UtilApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/OdsayApiController.java
> [백] 서버에서 ODsay API 호출

- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/OdsayApiController.java
- front-end/src/OdsayApi.js
- front-end/src/routes/Path/PathContainer.js
- 클라이언트에서 ODsay API 호출을 하던 것을 서버로 변경함.
- 추후 퍼스널모빌리티와 경로를 제시해야하는 점을 봤을 때 서버에서 한번에 가공하여 전해주는 것이 좋으므로 변경함
- 기존 클라이언트 api 코드는 주석처리 해놓고 담당 조원과 확인이 끝났을 시 삭제 예정
> Path 길찾기 api 변경

- front-end/src/routes/Member/SearchPw/SearchPwPresenter.js
- front-end/src/routes/Member/SignUp/SignUpContainer.js
- front-end/src/routes/Member/SignUp/SignUpPresenter.js
> [프론트] 에러 수정

- BackEnd/src/main/java/com/capstone/pathproject/config/rest/TmapConfiguration.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/TmapApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/tmap/path/Features.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/tmap/path/Geometry.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/tmap/path/Properties.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/tmap/path/WalkPathDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/TmapService.java
> [백] Tmap API 보행자 경로 기능 추가

- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Member.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/MemberGender.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/member/MemberDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitDb.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitMemberService.java
- BackEnd/src/test/java/com/capstone/pathproject/controller/MemberApiControllerTest.java
- BackEnd/src/test/java/com/capstone/pathproject/repository/member/CardRepositoryTest.java
- member, business, admin 회원 1명씩 DB 저장
- member 회원 10명 저장
- business 회원 10명 저장
> 스프링 실행시 DB 값 자동 저장

- BackEnd/src/main/java/com/capstone/pathproject/init/InitDb.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitMobilityCompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitMobilityService.java
- 퍼스널 모빌리티 제휴업체 자동 생성
- 퍼스널 모빌리티 기기 자동 생성
> [백] 모빌리티 회사 및 기기 자동 생성

- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/CarPoolPostApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarPostService.java
- front-end/package-lock.json
- front-end/package.json
- front-end/public/index.html
- front-end/src/components/Router.js
- front-end/src/routes/CarPool/CarPoolAdd.js
- front-end/src/routes/CarPool/CarPoolContents.js
- front-end/src/routes/CarPool/CarPoolPresenter.js
> [백,프론트] 카풀 차량경로 표시 및 기타기능

- BackEnd/src/main/java/com/capstone/pathproject/repository/mobility/MobilityRepository.java
> [백] 퍼스널 모빌리티 조회 로직 수정

- BackEnd/src/main/java/com/capstone/pathproject/repository/mobility/MobilityRepository.java
- 기존 연관관계인 제휴업체를 계속 조회날리는 N+1 문제가 생겨서 처음 조회할 때 left join을 시켜 쿼리 한방에 해결함.
> [백] 퍼스널모빌리티 조회 성능 개선

- BackEnd/src/main/java/com/capstone/pathproject/controller/mobility/MobilityApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/OdsayApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/TmapApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/Info.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/SubPath.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/TransPathDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/tmap/path/Geometry.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/tmap/path/Properties.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/tmap/path/WalkPathDto.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
> [백] 퍼스널모빌리티 활용 길찾기 기능 추가

- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
퍼스널 모빌리티를 활용하는 시간이 걷는 속력으로 되어있어서 수정함
> [백] 퍼스널 모빌리티를 활용한 길찾기 속력수정

- front-end/src/MapApi.js
- front-end/src/OdsayApi.js
- front-end/src/TmapApi.js
- front-end/src/routes/CarPool/CarPoolAdd.js
- front-end/src/routes/CarPool/CarPoolContents.js
- front-end/src/routes/CarPool/CarPoolPresenter.js
- front-end/src/routes/Community/CommunityAdd.js
- front-end/src/routes/Community/CommunityContainer.js
- front-end/src/routes/Community/CommunityContents.js
- front-end/src/routes/Community/CommunityPresenter.js
- front-end/src/routes/Community/index.js
- front-end/src/routes/Member/Company/CompCreate/CompCreateContainer.js
- front-end/src/routes/Member/Company/CompManage/CompManageContainer.js
- front-end/src/routes/Member/Company/CompManage/ItemEdit/ItemEdit.js
- front-end/src/routes/Member/Company/CompManage/ItemEdit/ItemEditContainer.js
- front-end/src/routes/Member/Company/CompManage/Items/Item.js
- front-end/src/routes/Member/Company/CompManage/Items/ItemContainer.js
- front-end/src/routes/Member/Company/CompStore/CompStore.js
- front-end/src/routes/Member/Company/ItemBasic/ItembasicMain.js
- front-end/src/routes/Member/SearchId/SearchIdContainer.js
- front-end/src/routes/Member/SearchPw/SearchPwContainer.js
- front-end/src/routes/Member/SearchPw/SearchPwPresenter.js
- front-end/src/routes/Member/SignUp/SignUpContainer.js
- front-end/src/routes/Mobility/Bus/index.js
- front-end/src/routes/Mobility/Subway/index.js
- front-end/src/routes/WalkPath/WalkPathContainer.js
- front-end/src/routes/WalkPath/WalkPathPresenter.js
- front-end/src/routes/WalkPath/index.js
Reverts YGUniv-NonSleep/Path#167
> Revert "[프론트] 폴더 구조 수정"

- BackEnd/src/main/java/com/capstone/pathproject/config/rest/TmapConfiguration.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/OdsayApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/Info.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/SubPath.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/mobility/MobilityRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/mobility/MobilityService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/TmapService.java
출발지점에서 퍼스널 모빌리티를 사용하여 찾은 경로에서 2가지로 나뉜다.
1. 도착지점에서 퍼스널 모빌리티를 타지 않은 시간, 요금
2. 도착지점에서 퍼스널 모빌리티를 탄 시간, 요금
> [백] 퍼스널 모빌리티 활용한 길찾기 기능 추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/TmapApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/graph/GraphPos.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/TmapService.java
출발 -> 모빌리티 -> 목적지 경로를 주는 길찾기 기능 추가
> [백] 출발 -> 모빌 -> 목적지 길찾기 기능 추가

- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/TmapService.java
> [백] ODSay API 길찾기에서 출발지 도착지 좌표 추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/OdsayApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/TmapApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/TmapService.java
> [백] 버스, 지하철 각각 길찾기 추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/OdsayApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/TmapApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/TmapService.java
좌표 타입이 String에서 double 타입으로 변경
> [백] 길찾기 기능에서 좌표는 전부 double 타입변경

- BackEnd/src/main/java/com/capstone/pathproject/controller/rest/TmapApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/TmapService.java
> [백] 퍼스널 모빌리티 길찾기 기능 추가

- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/SubPath.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
> [백] 대중교통 길찾기에서 반환값 추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/order/OrderController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/CompMember.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Company.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Option.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Product.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/order/OptionComposition.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/order/Order.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/company/CompanyDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitCompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitDb.java
- BackEnd/src/main/java/com/capstone/pathproject/service/order/OrderService.java
[백]payment 수정, build 시 company 생성
> [백]payment 수정, build 시 company 생성

- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/Lane.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/PassStopList.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/Stations.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/odsay/path/SubPath.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
- 세부경로 타입, 버스 또는 지하철명, 소요시간 추가하여 응답
> [백] ODsay 길찾기 응답 값 추가

- BackEnd/src/main/java/com/capstone/pathproject/PathProjectApplication.java
- BackEnd/src/main/java/com/capstone/pathproject/config/AccountAwareAuditConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitDb.java
- 생성자와 수정자가 제대로 시큐리티 세션에서 사용자 정보를 못가져오는 에러 수정
> [백] Auditing 기능 에러 수정

- BackEnd/src/main/java/com/capstone/pathproject/config/rest/KakaoConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/config/rest/OdsayConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/config/rest/TmapConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/config/rest/TossConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/excpetion/ApiControllerAdvice.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/member/CardApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/member/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Card.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/response/Message.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/toss/billingKey/BillingKeyDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/rest/toss/billingKey/Card.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarPostRequestService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarPostService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarsService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/community/PostService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/company/CompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/member/CardService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/member/MemberService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/mobility/MobilityService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/order/OrderService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/product/ProductService.java
- BackEnd/src/test/java/com/capstone/pathproject/repository/member/CardRepositoryTest.java
- front-end/src/components/Router.js
- front-end/src/pages/Member/Card/Card.js
- front-end/src/pages/Member/MyPage/listItems.js
- front-end/src/pages/Member/hooks/useCard.js
- front-end/src/pages/Member/index.js
- 카드 등록 페이지 추가
- 토스 자동결제할 때 쓰는 카드 등록 기능 추가
- Configuration로 되어있던 클래스 이름들 전부 Config로 변경
- Message 빌더 생성자 메서드이름이 `createMessage` 였는데 이상하다 생각되어 기본값인 `builder`로 변경
- 토크 자동결제 카드 등록 기능 추가 (Card 테이블에 DB 저장 완료)
> [프론트, 백] Config 클래스 이름 변경, Message 빌더 생성자 이름 변경, 토스 카드 등록 기능 및 페이지 추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/member/CardApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/member/CardRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/member/query/CardQueryRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/member/CardService.java
- JPA에서 DTO로 바로 조회
- 페이지에 맞게 DTO로 바로 조회하므로 재사용성이 떨어짐. 따라서 새로운 QueryRepository 인터페이스를 만들어서 사용
> [백] 카드 등록 API 수정

- BackEnd/src/main/java/com/capstone/pathproject/config/AccountAwareAuditConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/service/community/PostService.java
- BackEnd/src/test/java/com/capstone/pathproject/repository/member/CardRepositoryTest.java
스프링 시큐리티 세션에서 사용자 정보를 가져올 시 null이 아닌 "anonymousUser"가 나옴
> [백] 스프링 시큐리티 인증 로직 수정

- BackEnd/src/main/java/com/capstone/pathproject/service/community/PostService.java
> [백] 게시글 등록기능 기술추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/member/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Company.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Member.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/member/MemberDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/member/SignupFormDto.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitMemberService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/member/MemberService.java
- BackEnd/src/test/java/com/capstone/pathproject/controller/MemberApiControllerTest.java
- BackEnd/src/test/java/com/capstone/pathproject/repository/member/CardRepositoryTest.java
- Entity가 Dto를 의존하던 관계 삭제
- builder 생성자 이름 전부 기본값으로 변경
> [백] 회원 Entity , Dto 수정

- BackEnd/src/main/java/com/capstone/pathproject/controller/post/PostApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/community/PostDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/community/ReplyCreatePostDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/community/UpdatePostDto.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/community/PostRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/community/PostService.java
- front-end/src/pages/Community/CommunityContents.js
- front-end/src/pages/Community/CommunityMain.js
- front-end/src/pages/Community/hooks/useBoardContents.js
> [백] 게시글 Dto 분리 및 기능 수정

- front-end/package-lock.json
- front-end/src/components/Menubar.js
- front-end/src/hooks/useTokenReissue.js
- front-end/src/index.js
- front-end/src/pages/Member/Login/LoginMain.js
- front-end/src/pages/Member/MemberMain.js
- front-end/src/pages/Member/SearchId/SearchIdMain.js
- front-end/src/pages/Member/hooks/useLogin.js
- front-end/src/pages/Member/hooks/useMemberMain.js
- front-end/src/pages/Member/hooks/useSearchId.js
- front-end/src/store/index.js
- Redux 설치 및 적용 완료
- 회원 로그인 시 회원 정보 저장 완료
- 회원 정보는 이름, 아이디, 권한 저장
> [프론트] Redux 설치 및 적용과 회원정보 저장

- front-end/src/hooks/useTokenReissue.js
- front-end/src/store/index.js
> [프론트] Redux 회원 정보 추가

- BackEnd/src/main/java/com/capstone/pathproject/domain/order/OrderItem.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/order/OrderItemOption.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/order/CompositionRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/order/OptionCompositionRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/order/OrderService.java
composition -> OrderItem
OptionComposition -> OrderItemOption
> [백] ORDER_ITEM, ORDER_ITEM_OPTION 테이블 이름 변경

- BackEnd/src/main/java/com/capstone/pathproject/controller/member/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/member/MemberPaymentDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/order/OrderItemQueryDto.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/order/query/OrderItemQueryRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/order/query/PaymentQueryRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/member/MemberService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/order/OrderService.java
> [백] 회원 결제내역조회

- BackEnd/src/main/java/com/capstone/pathproject/service/rest/OdsayService.java
버스 정류장과 지하철 역 이름이 같이 있어서 구분을 못하므로 따로 나눠서 배열로 반환함
> [백] 길찾기 반환값 추가

- BackEnd/src/main/java/com/capstone/pathproject/init/InitDb.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitOrderService.java
> [백]order table row build시 생성

- front-end/src/pages/Member/Card/Card.js
- front-end/src/pages/Member/SearchId/SearchIdMain.js
- front-end/src/pages/Member/SearchPw/SearchPwMain.js
- front-end/src/pages/Member/SignUp/SignUpMain.js
- front-end/src/pages/Member/Update/UpdateMemMain.js
- front-end/src/pages/Member/hooks/useCard.js
- front-end/src/pages/Member/hooks/useSearchId.js
- front-end/src/pages/Member/hooks/useUpdateMem.js
- front-end/src/pages/Member/index.js
- 아이디 찾기, 비밀번호 찾기, 회원 가입, 회원 수정 페이지에서 돌아가기 버튼이 없어서 추가
- Redux로 회원정보 관리하므로 카드등록 기능 수정
> [프론트] 회원 관련 페이지 돌아가기 버튼 추가

- front-end/src/components/Router.js
- front-end/src/pages/Member/Cars/Cars.js
- front-end/src/pages/Member/Cars/addCars.js
- front-end/src/pages/Member/MyPage/listItems.js
- front-end/src/pages/Member/Update/UpdateMemMain.js
- front-end/src/pages/Member/hooks/useCars.js
- front-end/src/pages/Member/index.js
> [프론트] 차량 관리 페이지 및 등록 모달창 추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/CarPostRequestApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/carpool/CarPostRequest.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/carpool/CarPostRequestCreateDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/carpool/CarPostRequestDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/community/CreatePostDto.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/carpool/CarPostRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/community/PostRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarPostRequestService.java
- front-end/src/pages/CarPool/CarPoolContents.js
- front-end/src/pages/CarPool/CarPoolMain.js
- front-end/src/pages/CarPool/hooks/useCarPoolAdd.js
- front-end/src/pages/CarPool/hooks/useCarPoolContents.js
- front-end/src/pages/Community/CommunityContents.js
- front-end/src/pages/Community/hooks/useBoardContents.js
> [백]카풀 신청 등록기능

- BackEnd/src/main/java/com/capstone/pathproject/controller/member/CardApiController.java
- front-end/src/components/Menubar.js
- front-end/src/hooks/useTokenReissue.js
- 새로고침 했을 시 자동 로그인
- 토스 카드 등록 성공 요청과 실패 요청 시 홈페이지로 이동
> 새로고침 시 자동 로그인, 회원 카드 등록 성공과 실패 요청시 홈 이동

- BackEnd/src/main/java/com/capstone/pathproject/controller/member/CardApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/service/member/CardService.java
- front-end/src/pages/Member/Card/Card.js
- front-end/src/pages/Member/Card/CardMain.js
- front-end/src/pages/Member/SignUp/SignUpMain.js
- front-end/src/pages/Member/hooks/useCard.js
> [프론트, 백] 카드 삭제 기능 완료

- BackEnd/src/main/java/com/capstone/pathproject/controller/company/CompanyApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitCompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitProductService.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/company/CompanyRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/company/CompanyService.java
[백] InitCompany기본값 수정, 카테고리로 업체검색 추가
> [백] InitCompany기본값 수정, 카테고리로 업체검색

- front-end/src/pages/Member/Cars/Cars.js
- front-end/src/pages/Member/Cars/addCars.js
- front-end/src/pages/Member/hooks/useCars.js
> [프론트] 차량등록 이미지 기능 추가

- BackEnd/src/main/java/com/capstone/pathproject/init/InitCardService.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitDb.java
- BackEnd/src/main/java/com/capstone/pathproject/util/CookieUtil.java
> [백] 회원 카드 DB 자동등록

- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Company.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/member/Member.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/company/CompanyDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitCompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/company/CompanyRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/company/CompanyService.java
> [백]company Column 추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/member/MemberApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/order/AmountByDayDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/order/MemberPaymentDto.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/order/query/PaymentQueryRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/member/MemberService.java
- front-end/src/pages/Member/MemberMain.js
- front-end/src/pages/Member/MyPage/Chart.js
- front-end/src/pages/Member/MyPage/Deposits.js
- front-end/src/pages/Member/MyPage/Orders.js
- front-end/src/pages/Member/MyPage/OrdersList.js
- front-end/src/pages/Member/MyPage/listItems.js
- front-end/src/pages/Member/hooks/useMemberMain.js
- 회원 결제내역 조회
- 회원 결제내역 차트 추가
- 회원 결제내역 이번달 총 요금 추가
- 회원 이번달 결제내역 조회하여 날짜와 요금 반환
> 회원 마이페이지 기능 추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/company/CompanyApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/company/FindCompanyDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/company/LocationDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/product/ProductDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/company/CompanyRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/company/CompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/product/ProductService.java
> [백] Company 좌표 조회, 오류 수정

- front-end/src/pages/Member/Payment/PaymentMain.js
> [프론트] 결제내역 페이지 버튼 이름 수정

- BackEnd/src/main/java/com/capstone/pathproject/controller/company/CompanyApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Company.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/DetailOption.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Option.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/ProdBasic.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Product.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/company/CompanyDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/product/DetailOptionDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/product/OptionDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/product/ProdBasicDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/product/ProductDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/company/CompanyRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/company/CompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/product/ProductService.java
> [백]domain -> Dto 의존성 제거

- BackEnd/src/main/java/com/capstone/pathproject/security/oauth/NaverUserInfo.java
- BackEnd/src/main/java/com/capstone/pathproject/security/oauth/OAuth2UserInfo.java
- BackEnd/src/main/java/com/capstone/pathproject/security/oauth/PrincipalOauth2UserService.java
> [백] NAVER 회원가입 및 로그인 기능 완료

- BackEnd/src/main/java/com/capstone/pathproject/security/oauth/FacebookUserInfo.java
- BackEnd/src/main/java/com/capstone/pathproject/security/oauth/KakaoUserInfo.java
- BackEnd/src/main/java/com/capstone/pathproject/security/oauth/PrincipalOauth2UserService.java
- front-end/src/pages/Member/Login/LoginMain.js
- FACEBOOK, KAKAO 회원가입 및 로그인 기능 완료
> [프론트, 백] FACKBOOK, KAKAO 회원가입 및 로그인 완료

- front-end/src/pages/Member/Login/LoginMain.js
> [프론트] 로그인 페이지 css 수정

- BackEnd/src/main/java/com/capstone/pathproject/controller/mobility/MobilityApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/mobility/ReserveMobilRequest.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/mobility/ReserveMobilResponse.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/mobility/MobilityReserveRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/mobility/MobilityService.java
- 퍼스널 모빌리티 예약 시 이미 예약중인 퍼스널 모빌리티가 있는지 검증
- 예약중인 퍼스널 모빌리티가 있는지 조회 기능 추가
> [백] 퍼스널 모빌리티 예약 로직 수정, 예약중인 퍼스널 모빌리티 조회 추가

- BackEnd/src/main/java/com/capstone/pathproject/dto/mobility/LocationMobilityDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/mobility/ReserveMobilResponse.java
- BackEnd/src/main/java/com/capstone/pathproject/service/rest/TmapService.java
> [백] 퍼스널 모빌리티 응답값 수정

- BackEnd/src/main/java/com/capstone/pathproject/dto/company/FindCompanyDto.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/company/CompanyRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/product/ProductRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/company/CompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/product/ProductService.java
> [백] 업체 거리 조회 수정

- BackEnd/src/main/java/com/capstone/pathproject/controller/product/ProductApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/product/FindProductDto.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/product/ProductRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/product/ProductService.java
> [백]product find

- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Option.java
> [백]option table name change

- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityReserve.java
> [백] 퍼스널모빌리티 예약 엔티티 수정

- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/CarPoolPostApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/CarsAPIController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/post/PostApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/carpool/Cars.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Option.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarPostService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarsService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/community/PostService.java
- front-end/src/pages/CarPool/CarPoolContents.js
- front-end/src/pages/CarPool/hooks/useCarPoolAdd.js
- front-end/src/pages/CarPool/hooks/useCarPoolContents.js
- front-end/src/pages/Community/CommunityContents.js
- front-end/src/pages/Community/hooks/useBoardAdd.js
- front-end/src/pages/Community/hooks/useBoardContents.js
- front-end/src/pages/Member/Cars/Cars.js
- front-end/src/pages/Member/hooks/useCars.js
> [백,프론트] 게시글.카풀 사진 보이기 및 기능 추가

- front-end/src/pages/CarPool/CarPoolContents.js
- front-end/src/pages/CarPool/hooks/useCarPoolContents.js
> [프론트]카풀 신청자 위치찍기

- BackEnd/src/main/java/com/capstone/pathproject/controller/mobility/MobilityApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/mobility/MobilityType.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/mobility/MobilityRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/mobility/MobilityService.java
- front-end/src/pages/Path/PathMain.js
- front-end/src/pages/Path/hooks/useInputForm.js
- 길찾기에서 사용자 입력이 끝난 후 0.5초 뒤에 검색
- 퍼스널 모빌리티에서 BIKE와 KICKBOARD 둘 다 조회 추가
> [프론트, 백] 0.5초뒤 검색 기능, 퍼스널 모빌리티 조회 수정

- BackEnd/src/main/java/com/capstone/pathproject/config/SecurityConfig.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/UtilApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/order/SaveOrderDto.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitCompanyService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/product/ProductService.java
- front-end/src/pages/TosspaymentsTest/PaymentsPresenter.js
> [백]company 좌표 수정

- front-end/src/pages/Path/PathMain.js
- front-end/src/pages/Path/hooks/useInputForm.js
- 출발지 -> 첫정류장까지 퍼스널 모빌리티 경로 추가
- 마지막 정류장 -> 목적지까지 퍼스널 모빌리티 경로 추가
> [프론트] 통합 길찾기 - 퍼스널 모빌리티 경로 추가 완료

- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Company.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/order/Order.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/company/CompanyDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/order/OrderDto.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitProductService.java
- front-end/src/pages/Company/CompManage/CompManageMain.js
> [백]company DB change

- BackEnd/src/main/java/com/capstone/pathproject/service/rest/TmapService.java
- front-end/src/api/MapApi.js
- front-end/src/pages/Path/PathList.js
- front-end/src/pages/Path/PathMain.js
- front-end/src/pages/Path/hooks/useInputForm.js
- 퍼스널 모빌리티 선택시 시간과 요금 수정
- 다른 경로 수정시 시간과 요금 초기화
- Tmap API 보행자 경로에서 속도가 반영되지 않아 직접 구하는걸로 수정
> 통합길찾기 - 퍼스널 모빌리티 선택시 시간과 요금 수정

- front-end/src/components/Icon.js
- front-end/src/pages/Path/PathMain.js
- front-end/src/pages/Path/hooks/useInputForm.js
- 버스만 사용한 길찾기 완료
- 지하철만 사용한 길찾기 완료
> [프론트] 버스 길찾기, 지하철 길찾기 기능 추가

- front-end/src/components/Icon.js
- front-end/src/pages/Path/PathList.js
- front-end/src/pages/Path/PathMain.js
- front-end/src/pages/Path/hooks/useInputForm.js
- 검색 메뉴바 아이콘 선택시 색 변함
- 검색하고나서 다른곳도 바로 검색가능
> [프론트] 퍼스널 모빌리티 길찾기 추가 및 수정

- front-end/src/api/OdsayApi.js
- front-end/src/pages/Path/hooks/useInputForm.js
개발자하는 과정에서 log를 찍은것을 지우지않아서 전부 삭제
> [프론트] 길찾기부분 log제거

- front-end/src/pages/Path/PathList.js
- front-end/src/pages/Path/PathMain.js
> [프론트] 퍼스널모빌리티 길찾기 내용 수정

- front-end/src/api/TmapApi.js
- front-end/src/pages/Path/PathList.js
- front-end/src/pages/Path/hooks/useInputForm.js
> [프론트] 도보 길찾기 기능 추가

- front-end/src/pages/Path/hooks/useInputForm.js
- 출발지, 도착지, 타입으로 중복된 것을 제거하고 최근 검색에 넣는 방식에서 타입 검증을 삭제
> [프론트] 타입별 검색목록 삭제

- front-end/src/pages/Path/hooks/useInputForm.js
This reverts commit 1f2ebb63566c04b96fe633b386bb212c94b6c7bd, reversing
changes made to 07a20d9db68b26c84fbe705f9cf1fa7e0f80a5f7.
> Revert "Merge pull request #304 from YGUniv-NonSleep/PathHistory"

- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/CarPostRequestApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/carpool/CarPostRequest.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/carpool/CarPostRequestCreateDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/carpool/CarPostRequestDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/carpool/CarPostRequestRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarPostRequestService.java
- front-end/package-lock.json
- front-end/package.json
- front-end/src/components/Menubar.js
- front-end/src/components/Router.js
- front-end/src/pages/Confirmation/Confirmation.js
- front-end/src/pages/Confirmation/SendingConfirm.js
- front-end/src/pages/Member/MyPage/listItems.js
> [백,프론트] 카풀 알림기능

- front-end/src/pages/Confirmation/SendingConfirm.js
> [프론트] 카풀 알림기능 수정

- front-end/package-lock.json
- front-end/package.json
> [프론트]pakage-lock 오류해결

- BackEnd/src/main/java/com/capstone/pathproject/controller/product/ProductApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/company/Product.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitDb.java
- BackEnd/src/main/java/com/capstone/pathproject/service/product/ProductService.java
- front-end/package-lock.json
- front-end/src/pages/Company/CompManage/Items/ItemsMain.js
- front-end/src/pages/Company/CompManage/hooks/useCompItems.js
> [프론트]product crud

- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/BoardingApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/CarPoolPostApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/OperationApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/carpool/CarPost.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/carpool/CarPostDTO.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/carpool/OperationRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/BoardingService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarPostService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/OperationService.java
- front-end/src/pages/CarPool/hooks/useCarPoolRequest.js
- front-end/src/pages/Confirmation/Confirmation.js
- front-end/src/pages/Confirmation/SendingConfirm.js
- front-end/src/pages/History/Boarding.js
- front-end/src/pages/History/Operation.js
> [백,프론트] 카풀

- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/BoardingApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/OperationApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/domain/carpool/OperationDetail.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/carpool/BoardingDetailDto.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/carpool/OperationDetailDto.java
- BackEnd/src/main/java/com/capstone/pathproject/init/InitDb.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/carpool/BoardingRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/carpool/OperationRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/BoardingService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/OperationService.java
- front-end/src/pages/Confirmation/SendingConfirm.js
- front-end/src/pages/History/Boarding.js
- front-end/src/pages/History/Operation.js
> [백]운행,탑승내역 수정

- app/.idea/misc.xml
- app/app/src/main/AndroidManifest.xml
- app/app/src/main/java/kr/tutorials/pathprojectapp/BasketRvAdapter.kt
- app/app/src/main/java/kr/tutorials/pathprojectapp/CompanyActivity.kt
- app/app/src/main/java/kr/tutorials/pathprojectapp/CompanyRvAdapter.kt
- app/app/src/main/java/kr/tutorials/pathprojectapp/MainActivity.kt
- app/app/src/main/java/kr/tutorials/pathprojectapp/MainRvAdapter.kt
- app/app/src/main/java/kr/tutorials/pathprojectapp/dto/BasketDto.kt
- app/app/src/main/java/kr/tutorials/pathprojectapp/dto/ProductDto.kt
- app/app/src/main/res/layout/activity_company.xml
- app/app/src/main/res/layout/basket_rv_item.xml
- app/app/src/main/res/layout/company_rv_item.xml
- app/app/src/main/res/layout/main_rv_item.xml
> [앱] 업체 메뉴 페이지 추가

- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/CarPostRequestApiController.java
- BackEnd/src/main/java/com/capstone/pathproject/controller/carpool/CarsAPIController.java
- BackEnd/src/main/java/com/capstone/pathproject/dto/carpool/OperationDetailDto.java
- BackEnd/src/main/java/com/capstone/pathproject/repository/carpool/CarPostRequestRepository.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarPostRequestService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/CarsService.java
- BackEnd/src/main/java/com/capstone/pathproject/service/carpool/OperationService.java
- front-end/src/pages/CarPool/CarPoolContents.js
- front-end/src/pages/CarPool/CarPoolMain.js
- front-end/src/pages/CarPool/hooks/useCarPoolContents.js
- front-end/src/pages/Confirmation/Confirmation.js
- front-end/src/pages/Confirmation/SendingConfirm.js
> [백.프론트]카풀 운행.탑승내역수정
